import schemaMixin from "../mixins/schemaMixin";
import mix from "../mixins/mix";
var schema = {
  title: "Supplier Payments",
  recordName: "SupplierPayments",
  goBackTo: "SupplierPayments",
  fields: [
    {
      label: " Date",
      inputType: "date",
      name: "date",
      required: true,
    },
    {
      label: "Initiator",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "name",
      name: "initiator",
      optionSource: "tbl_Users",
      optionDisplayField: ["name", "other_details"],
    },

    {
      label: "Program Name",
      inputType: "select_multilevel",
      optionSource: "tbl_Programs",
      filterOptions: { tblToFilter: "tbl_Jobs", filterOn: "program_name" },
      name: "program_name",
    },
    {
      label: "Project Name",
      inputType: "select",
      optionSource: "tbl_Projects",
      name: "project_name",
    },
    {
      label: "ETCS Job #",
      inputType: "select_multilevel",
      optionSource: "tbl_Jobs",
      selectOptions: { value: "job_name", name: "job_name" },
      name: "ETCS_Job_#",
    },
    {
      label: "Description",
      inputType: "textArea",
      name: "description",
    },
    {
      label: "Supplier",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "short_name",
      name: "supplier_name",
      optionSource: "tbl_Suppliers",
      optionDisplayField: ["short_name", "country"],
    },
    {
      label: "ETCS PO No",
      inputType: "text",
      name: "etcs_po_no",
    },
    {
      label: "Supplier Invoice No",
      inputType: "text",
      name: "supplier_invoice_no",
    },
    {
      label: "Supplier Invoice Date",
      inputType: "date",
      name: "supplier_invoice_date",
      required: true,
    },
    {
      label: "Supplier Invoice Amount(USD)",
      inputType: "number",
      prefix: "$",
      name: "supplier_invoice_amount",
      controls: false,
      step: "0.01",
      required: true,
    },
    {
      label: "Approved By",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "name",
      name: "approved_by",
      optionSource: "tbl_Users",
      optionDisplayField: ["name", "other_details"],
    },
    {
      label: "Payment Release Date",
      inputType: "date",
      name: "payment_release_date",
      required: true,
    },
    {
      label: "Homeline Deductions(USD)",
      inputType: "number",
      prefix: "$",
      name: "homeline_deductions",
      controls: false,
      step: "0.01",
      required: true,
    },

    // {
    //   label: "Final Payment",
    //   inputType: "number",
    //   name: "final_payment",
    //   controls: false,
    //   step: "0.01",
    // },
    {
      label: "Final Payment(USD)",
      inputType: "number_computed",
      prefix: "$",
      computeElements: [
        "substract",
        "supplier_invoice_amount",
        "homeline_deductions",
      ],
      name: "final_payment",
      controls: false,
      step: "0.01",
    },

    {
      label: "Attach File(against invoice)",
      inputType: "file",
      name: "invoice_attachments",
    },
    {
      label: "Attach File(againts payments)",
      inputType: "file",
      name: "payment_attachments",
    },
  ],
  filterSchema: {
    title: "Filter Supplier Payments",
    filters: [
      {
        label: "Initiator",
        fld: "initiator",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      {
        label: "Req-ID",
        fld: "id",
        type: "text",
        value: "",
      },
      {
        label: "Supplier",
        fld: "supplier_name",
        type: "select",
        value: "",
        keyRenderFld: "short_name",
        optionSource: "tbl_Suppliers",
        optionDisplayField: ["short_name", "country"],
      },
      {
        label: "Program Name",
        fld: "program_name",
        inputType: "select",
        optionSource: "tbl_Programs",
        name: "program_name",
        type: "select",
        value: "",
      },
      {
        label: "Project Name",
        fld: "project_name",
        inputType: "select",
        optionSource: "tbl_Projects",
        name: "project",
        type: "select",
        value: "",
      },
      {
        label: "ETCS Job #",
        fld: "ETCS_Job_#",
        optionSource: "tbl_Jobs",
        optionDisplayField: ["job_name"],
        type: "select",
        value: "",
      },
      {
        label: "ETCS PO No",
        fld: "etcs_po_no",
        type: "text",
        value: "",
      },
      {
        label: "Supplier Invoice No",
        fld: "supplier_invoice_no",
        type: "text",
        value: "",
      },
      {
        label: "Supplier Invoice Amount(USD)",
        fld: "supplier_invoice_amount",
        type: "number",
        value: "",
      },

      {
        label: "Approved By",
        fld: "approved_by",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      // Dates Filter
      {
        fld: "supplier_invoice_date",
        label: "Supplier Invoice Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "due_date",
        label: "Due Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "payment_release_date",
        label: "Payment Release Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
    ],
  },
  mailOptions: {
    // to: ["notifications.borl@gmail.com"],
    // cc: ["sharma.pritam3111@gmail.com", "pritamiitian@gmail.com"],
    // editTo: ["notifications.borl@gmail.com"],
    to: ["priya@etcsinc.com"],
    cc: [
      "ravi@etcsinc.com",
      "sushant@etcsinc.com",
      "ronald@etcsinc.com",
      "ramprasad@etcsinc.com",
      "gurneet@etcsinc.com",
    ],
    edtiTo: [
      "sushant@etcsinc.com",
      "ramprasad@etcsinc.com",
      "gurneet@etcsinc.com",
    ],
    ignoreModelFields: ["invoice_attachments", "payment_attachments"],
    subject: "Supplier Payments",
    reqDateField: "date",
    line1: "Dear Priya,\n Kindly process the payment for the following: :",
    editLine1: "Kindly note the changes done in the below mentioned request :",
    reminderLine1:
      "Hi Priya, Please confirm the status on this open request : ",

    end: "Thanks & Regards",
    requestee: "",
  },
};

const mixed = mix({}, schema, schemaMixin);

export default mixed;
