import schemaMixin from "../mixins/schemaMixin";
import mix from "../mixins/mix";

var schema = {
  title: "Homeline Expenses",
  recordName: "HomelineExpenses",
  goBackTo: "HomelineExpense",
  fields: [
    {
      label: "Date",
      inputType: "date",
      name: "req_date",
      required: true,
    },
    {
      label: "Initiator",
      inputType: "select",
      isForeignKey: true,
      name: "initiator",
      keyRenderFld: "name",
      optionSource: "tbl_Users",
      optionDisplayField: ["name", "other_details"],
    },
    {
      label: "Supplier Name",
      inputType: "select",
      name: "supplier_name",
      isForeignKey: true,
      keyRenderFld: "short_name",
      optionSource: "tbl_Suppliers",
      optionDisplayField: ["short_name", "country"],
    },
    {
      label: "Program Name",
      inputType: "select_multilevel",
      optionSource: "tbl_Programs",
      filterOptions: { tblToFilter: "tbl_Jobs", filterOn: "program_name" },
      name: "program_name",
    },
    {
      label: "Project Name",
      inputType: "select",
      optionSource: "tbl_Projects",
      name: "project_name",
    },
    {
      label: "Job No",
      inputType: "select_multilevel",
      optionSource: "tbl_Jobs",
      selectOptions: { value: "job_name", name: "job_name" },
      name: "job_no",
    },
    {
      label: "ETCS PO No",
      inputType: "text",
      name: "etcs_po_no",
    },
    {
      label: "Supplier Invoice No",
      inputType: "text",
      name: "supplier_invoice_no",
    },
    {
      label: "Supplier Invoice Date",
      inputType: "date",
      name: "supplier_invoice_date",
      required: true,
    },
    {
      label: "Supplier Invoice Amount(USD)",
      inputType: "number",
      prefix: "$",
      name: "supplier_invoice_amount",
      controls: false,
      step: "0.01",
      required: true,
    },
    {
      label: "Approved By",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "name",
      optionSource: "tbl_Users",
      optionDisplayField: ["name", "other_details"],
      name: "approved_by",
    },
    {
      label: "Final Payment(USD)",
      inputType: "number",
      prefix: "$",
      name: "final_payment",
      controls: false,
      step: "0.01",
    },
    {
      label: "Payment Release Date",
      inputType: "date",
      name: "payment_release_date",
      required: true,
    },
    {
      label: "Description",
      inputType: "textArea",
      name: "description",
    },
    {
      label: "Payment status",
      inputType: "instant_select",
      name: "payment_status",
      options: ["Open", "Closed", "In-Process"],
      slected: "Open",
    },
    {
      label: "Attach File",
      inputType: "file",
      name: "receipts",
    },
  ],
  filterSchema: {
    title: "Filter Supplier Payments",
    filters: [
      {
        label: "Initiator",
        fld: "initiator",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      {
        label: "Req-ID",
        fld: "id",
        type: "text",
        value: "",
      },
      {
        label: "Supplier",
        fld: "supplier_name",
        type: "select",
        value: "",
        keyRenderFld: "short_name",
        optionSource: "tbl_Suppliers",
        optionDisplayField: ["short_name", "country"],
      },
      {
        label: "Program Name",
        fld: "program_name",
        inputType: "select",
        optionSource: "tbl_Programs",
        name: "program_name",
        type: "select",
        value: "",
      },
      {
        label: "Project Name",
        fld: "project_name",
        inputType: "select",
        optionSource: "tbl_Projects",
        name: "project",
        type: "select",
        value: "",
      },

      {
        label: "ETCS PO No",
        fld: "etcs_po_no",
        type: "text",
        value: "",
      },
      {
        label: "Supplier Invoice No",
        fld: "supplier_invoice_no",
        type: "text",
        value: "",
      },
      {
        label: "Supplier Invoice Amount(USD)",
        fld: "supplier_invoice_amount",
        type: "number",
        value: "",
      },
      {
        label: "Homeline Deductions(USD)",
        fld: "homeline_deductions",
        type: "number",
        value: "",
      },

      {
        label: "Approved By",
        fld: "approved_by",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      // Dates Filter
      {
        fld: "supplier_invoice_date",
        label: "Supplier Invoice Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "due_date",
        label: "Due Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "payment_release_date",
        label: "Payment Release Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
    ],
  },
};

const mixed = mix({}, schema, schemaMixin);

export default mixed;
