import schemaMixin from "../mixins/schemaMixin";
import mix from "../mixins/mix";
var schema = {
  title: "Customer PO Request",
  recordName: "CustomerPORequest",
  goBackTo: "POCustomer",

  fields: [
    {
      label: "Request Date",
      inputType: "date",
      name: "request_date",
      required: true,
    },
    {
      label: "Initiator",
      inputType: "select",
      isForeignKey: true,
      name: "initiator",
      keyRenderFld: "name",
      optionSource: "tbl_Users",
      optionDisplayField: ["name", "other_details"],
    },
    {
      label: "Program Name",
      inputType: "select_multilevel",
      optionSource: "tbl_Programs",
      filterOptions: { tblToFilter: "tbl_Jobs", filterOn: "program_name" },
      name: "program_name",
    },
    {
      label: "Project Name",
      inputType: "select",
      optionSource: "tbl_Projects",
      name: "project_name",
    },
    {
      label: "ETCS Quote #",
      inputType: "text",
      name: "ETCS_Quote_#",
    },
    {
      label: "Description",
      inputType: "text",
      name: "description",
    },
    {
      label: "Customer Name",
      inputType: "select",
      name: "customer_name",
      isForeignKey: true,
      keyRenderFld: "short_name",
      optionSource: "tbl_Customers",
      optionDisplayField: ["short_name", "country"],
    },
    {
      label: "Total Entries",
      inputType: "number",
      linkedGroup: "accounts",
      min: 1,
      max: 10,
      name: "total_entries",
    },

    {
      inputType: "group",
      label: "Total Entries",
      name: "accounts",
      rowCount: 1,
      linkedRowCountFld: "total_entries",
      validation: "min:2,length",
      repeatable: true,
      "add-label": "+ Add platform",
      value: [{}],
      fields: [
        {
          label: "",
          placeholder: "Job #",
          inputType: "select_multilevel",
          optionSource: "tbl_Jobs",
          selectOptions: { value: "job_name", name: "job_name" },
          name: "job_no",
        },
        // {
        //   label: "",
        //   placeholder:"",
        //   inputType: "instant_select",
        //   options: ["$", "₹"],
        //   slected: "$",
        //   name: "curr",
        // },
        {
          label: "",
          placeholder: "Enter cost in $",
          inputType: "number",
          prefix: "$",
          name: "amount",
          controls: false,
          step: "0.01",
          required: true,
        },
      ],
    },
    {
      label: "Total Value",
      inputType: "number_aggregate",
      prefix: "$",
      computeElements: {
        aggregateOver: "accounts",
        aggregateBy: "amount",
      },
      name: "total_value",
      controls: false,
      step: "0.01",
    },

    {
      label: "Due Date",
      inputType: "date",
      name: "due_date",
      required: true,
    },
    {
      label: "Responsible Person",
      inputType: "select",
      isForeignKey: true,
      optionSource: "tbl_Users",
      keyRenderFld: "name",
      optionDisplayField: ["name", "other_details"],
      name: "responsible_person",
    },
    {
      label: "Customer PO #",
      inputType: "text",
      name: "customer_PO_#",
    },
    {
      label: "PO status",
      inputType: "instant_select",
      options: ["Open", "Closed", "In-Process"],
      slected: "Open",
      name: "po_status",
    },
    {
      label: "Close Date",
      inputType: "date",
      name: "close_date",
      required: true,
    },

    {
      label: "Notes/Description",
      inputType: "textArea",
      name: "notes",
    },
    {
      label: "Attach File",
      inputType: "file",
      name: "poFile",
    },
  ],
  filterSchema: {
    title: "Filter Customer PO Records",
    filters: [
      {
        label: "Initiator",
        fld: "initiator",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      {
        label: "Req-ID",
        fld: "id",
        type: "text",
        value: "",
      },
      {
        label: "Responsible Person",
        fld: "initiator",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },

      {
        label: "Customer Name",
        fld: "customer_name",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Customers",
        optionDisplayField: ["short_name", "country"],
      },
      {
        label: "Program Name",
        fld: "program_name",
        inputType: "select",
        optionSource: "tbl_Programs",
        name: "program_name",
        type: "select",
        value: "",
      },
      {
        label: "Project Name",
        fld: "project_name",
        inputType: "select",
        optionSource: "tbl_Projects",
        name: "project",
        type: "select",
        value: "",
      },
      {
        label: "ETCS Quote #",
        fld: "ETCS_Quote_#",
        type: "text",
        value: "",
      },
      {
        label: "Customer PO #",
        fld: "customer_PO_#",
        type: "text",
        value: "",
      },
      {
        label: "PO status",
        type: "instant_select",
        options: ["Open", "Closed", "In-Process"],
        value: "",
        fld: "po_status",
      },
      // {
      //   label: "Invoice Amount",
      //   fld: "invoice_amount",
      //   type: "text",
      //   value: "",
      // },
      // {
      //   label: "Final Payment",
      //   fld: "final_payment",
      //   type: "text",
      //   value: "",
      // },
      // Dates Filter
      {
        fld: "request_date",
        label: "Request Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "due_date",
        label: "Due Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "close_date",
        label: "Closed Date",
        type: "date_from_to",
        from: null,
        to: null,
      },

      // {
      //   label: "Project",
      //   fld: "",
      //   type: "select",
      //   value: "",
      // },
      // {
      //   label: "Job#",
      //   fld: "",
      //   type: "dependentSelect",
      //   value: "",
      // },
      // {
      //   label: "Company",
      //   fld: "",
      //   type: "select",
      //   value: "",
      // },
      // {
      //   label: "PO Value",
      //   fld: "",
      //   type: "text",
      //   value: "",
      // },
    ],
  },
  mailOptions: {
    // to: ["notifications.borl@gmail.com"],
    // cc: ["sharma.pritam3111@gmail.com", "pritamiitian@gmail.com"],
    // editTo: ["notifications.borl@gmail.com"],
    to: ["priya@etcsinc.com"],
    cc: [
      "ravi@etcsinc.com",
      "sushant@etcsinc.com",
      "ronald@etcsinc.com",
      "ramprasad@etcsinc.com",
      "gurneet@etcsinc.com",
    ],
    edtiTo: [
      "sushant@etcsinc.com",
      "ramprasad@etcsinc.com",
      "ronald@etcsinc.com",
      "gurneet@etcsinc.com",
    ],
    ignoreModelFields: ["poFile"],
    subject: "Customer PO Request",
    reqDateField: "request_date",
    line1:
      "Dear Priya,\n quote has been shared to the customer for the following :",
    editLine1: "Kindly note the changes done in the below mentioned request :",
    reminderLine1:
      "Hi Priya, Please confirm the status on this open request : ",

    end: "Thanks & Regards",
    requestee: "",
  },
};

const mixed = mix({}, schema, schemaMixin);

export default mixed;
