import schemaMixin from "../mixins/schemaMixin";
import mix from "../mixins/mix";

var schema = {
  title: "ETCS PO Request",
  recordName: "ETCSPORequest",
  goBackTo: "POETCS",
  fields: [
    {
      label: "Request Date",
      inputType: "date",
      name: "request_date",
      required: true,
    },
    {
      label: "Initiator",
      inputType: "select",
      isForeignKey: true,
      name: "initiator",
      keyRenderFld: "name",
      optionSource: "tbl_Users",
      optionDisplayField: ["name", "other_details"],
    },
    {
      label: "Program Name",
      inputType: "select_multilevel",
      optionSource: "tbl_Programs",
      filterOptions: { tblToFilter: "tbl_Jobs", filterOn: "program_name" },
      name: "program_name",
    },
    {
      label: "Project Name",
      inputType: "select",
      optionSource: "tbl_Projects",
      name: "project_name",
    },
    // {
    //   label: "Customer Name",
    //   inputType: "select",
    //   name: "customer_name",
    //   isForeignKey: true,
    //   keyRenderFld: "name",
    //   optionSource: "tbl_Customers",
    //   optionDisplayField: ["short_name", "country"],
    // },
    {
      label: "Company Name",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "short_name",
      name: "company_name",
      optionSource: "tbl_Suppliers",
      optionDisplayField: ["short_name", "country"],
    },
    // {
    //   label: "Supplier Name",
    //   inputType: "select",
    //   name: "supplier_name",
    //   isForeignKey: true,
    //   optionSource: "tbl_Suppliers",
    //   optionDisplayField: "name",
    // },
    {
      label: "Line Entries",
      inputType: "number",
      min: 1,
      max: 10,
      name: "rowCount",
      linkedGroup: "accounts",
    },

    {
      inputType: "group",
      name: "accounts",
      label: "Job + Value",
      rowCount: 1,
      linkedRowCountFld: "rowCount",
      validation: "min:2,length",
      repeatable: true,
      "add-label": "+ Add platform",
      value: [{}],
      fields: [
        {
          label: "",
          placeholder: "Select Job",
          inputType: "select_multilevel",
          optionSource: "tbl_Jobs",
          selectOptions: { value: "job_name", name: "job_name" },
          name: "job_no",
        },
        {
          label: "",
          placeholder: "Enter cost in $",
          inputType: "number",
          name: "cost",
          controls: false,
          step: "0.01",
          required: true,
        },
      ],
    },

    {
      label: "Total Job Value",
      inputType: "number_aggregate",
      computeElements: {
        aggregateOver: "accounts",
        aggregateBy: "cost",
      },
      name: "total_job_value",
      prefix: "$",
      controls: false,
      step: "0.01",
    },
    {
      label: "Item Name",
      inputType: "text",
      name: "item_name",
    },
    {
      label: "Item Catalogue No(If Any)",
      inputType: "text",
      name: "item_catalogu_no",
    },
    {
      label: "PO Value(USD)",
      inputType: "number",
      prefix: "$",
      name: "PO_value",
      controls: false,
      step: "0.01",
    },

    {
      label: "Due Date",
      inputType: "date",
      name: "due_date",
      required: true,
    },
    {
      label: "Responsible Person",
      inputType: "select",
      isForeignKey: true,
      optionSource: "tbl_Users",
      keyRenderFld: "name",
      optionDisplayField: ["name", "other_details"],
      name: "responsible_person",
    },
    {
      label: "ETCS PO #",
      inputType: "text",
      name: "ETCS_PO_#",
    },
    {
      label: "PO status",
      inputType: "instant_select",
      options: ["Open", "Closed", "In-Process"],
      slected: "Open",
      name: "po_status",
    },
    {
      label: "Close Date",
      inputType: "date",
      name: "close_date",
      required: true,
    },
    {
      label: "Notes/Description",
      inputType: "textArea",
      name: "notes",
    },
    {
      label: "Attach File",
      inputType: "file",
      name: "poFile",
    },
  ],
  filterSchema: {
    title: "Filter ETCS PO Records",
    filters: [
      {
        label: "Initiator",
        fld: "initiator",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      {
        label: "Req-ID",
        fld: "id",
        type: "text",
        value: "",
      },
      {
        label: "ETCS PO #",
        fld: "ETCS_PO_#",
        type: "text",
        value: "",
      },
      {
        label: "Company Name",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        fld: "company_name",
        optionSource: "tbl_Suppliers",
        optionDisplayField: ["short_name", "country"],
      },

      {
        label: "Program Name",
        fld: "program_name",
        inputType: "select",
        optionSource: "tbl_Programs",
        name: "program_name",
        type: "select",
        value: "",
      },
      {
        label: "Project Name",
        fld: "project_name",
        inputType: "select",
        optionSource: "tbl_Projects",
        name: "project",
        type: "select",
        value: "",
      },
      {
        label: "PO Value",
        fld: "PO_value",
        type: "text",
        value: "",
      },
      {
        label: "Responsible Person",
        fld: "responsible_person",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Users",
        optionDisplayField: "name",
      },
      {
        label: "PO Status",
        fld: "po_status",
        type: "instant_select",
        options: ["Open", "Closed", "In-Process"],
        value: "",
      },
      // Dates Filter
      {
        fld: "request_date",
        label: "Request Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "due_date",
        label: "Due Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "close_date",
        label: "Closed Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
    ],
  },
  mailOptions: {
    // to: ["notifications.borl@gmail.com"],
    // cc: ["sharma.pritam3111@gmail.com", "pritamiitian@gmail.com"],
    // editTo: ["notifications.borl@gmail.com"],
    to: ["priya@etcsinc.com"],
    cc: [
      "ravi@etcsinc.com",
      "sushant@etcsinc.com",
      "ronald@etcsinc.com",
      "ramprasad@etcsinc.com",
      "gurneet@etcsinc.com",
    ],
    edtiTo: [
      "sushant@etcsinc.com",
      "ronald@etcsinc.com",
      "ramprasad@etcsinc.com",
      "gurneet@etcsinc.com",
    ],
    ignoreModelFields: ["poFile"],
    subject: "ETCS PO Request",
    reqDateField: "request_date",
    line1: "Dear Priya,\n Kindly issue a PO for the following:",
    editLine1: "Kindly note the changes done in the below mentioned request :",
    reminderLine1:
      "Hi Priya, Please confirm the status on this open request : ",

    end: "Thanks & Regards",
    requestee: "",
  },
};

const mixed = mix({}, schema, schemaMixin);

export default mixed;
