import schemaMixin from "../mixins/schemaMixin";
import mix from "../mixins/mix";
var schema = {
  title: "Miscellaneous Shipments Records",
  recordName: "ShipmentMisc",
  fields: [
    {
      label: "Program Name",
      inputType: "select_multilevel",
      optionSource: "tbl_Programs",
      filterOptions: { tblToFilter: "tbl_Jobs", filterOn: "program_name" },
      name: "program_name",
    },
    {
      label: "Project",
      inputType: "select",
      optionSource: "tbl_Projects",
      name: "project",
    },
    {
      label: "Job No",
      inputType: "select_multilevel",
      optionSource: "tbl_Jobs",
      selectOptions: { value: "job_name", name: "job_name" },
      name: "job_no",
    },
    {
      label: "Description",
      inputType: "text",
      name: "description",
    },
    {
      label: "Customer Name",
      inputType: "select",
      name: "customer_name",
      isForeignKey: true,
      keyRenderFld: "short_name",
      optionSource: "tbl_Customers",
      optionDisplayField: ["short_name", "country"],
    },
    {
      label: "Die Shop",
      name: "die_shop",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "short_name",

      optionSource: "tbl_Suppliers",
      optionDisplayField: ["short_name", "country"],
    },
    {
      label: "Customer Contact",
      inputType: "text",
      name: "customer_contact",
    },

    {
      label: "ETCS Quote Value(USD)",
      inputType: "number",
      prefix: "$",
      name: "ETCS_quote_value",
      controls: false,
      step: "0.01",
      required: true,
    },
    {
      label: "Destination",
      inputType: "text",
      name: "destination",
    },
    {
      label: "PO To ETCS",
      inputType: "instant_select",
      name: "po_to_ETCS",
      options: ["Awaiting", "Yes", "No", "Email Approved"],
      required: true,
    },
    {
      label: "PO Value",
      inputType: "number",
      prefix: "$",
      name: "po_value",
      controls: false,
      step: "0.01",
      required: true,
    },

    {
      label: "Pickup Date",
      inputType: "date",
      name: "pickup_date",
    },

    {
      label: "Delivery Date",
      inputType: "date",
      name: "delivery_date",
    },

    {
      label: "Tracking Key",
      inputType: "text",
      name: "tracking_number",
    },
    {
      label: "Tracking Link",
      inputType: "link",
      name: "tracking_link",
    },
    {
      label: "Shipper",
      name: "shipper",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "short_name",
      optionSource: "tbl_Suppliers",
      optionDisplayField: ["short_name", "country"],
    },

    {
      label: "Responsible Party To Clear Custom",
      inputType: "select",
      isForeignKey: true,
      keyRenderFld: "short_name",
      optionSource: "tbl_Suppliers",
      optionDisplayField: ["short_name", "country"],
      name: "responsible_party_to_clear_custom",
    },
    {
      label: "Cost Approved(USD)",
      inputType: "number",
      name: "cost_approved",
      prefix: "$",
      controls: false,
      step: "0.01",
    },
    {
      label: "Duties + Taxes (Other Expenses)(USD)",
      inputType: "number_computed",
      prefix: "$",
      computeElements: ["substract", "final_invoice_to_etcs", "cost_approved"],
      name: "duties_taxes",
      controls: false,
      step: "0.01",
    },
    {
      label: "Final Invoice To ETCS(USD)",
      inputType: "number",
      prefix: "$",
      name: "final_invoice_to_ETCS",
      controls: false,
      step: "0.01",
    },
    // {
    //   label: "Total shipping cost To ETCS(USD)",
    //   inputType: "number",
    //   prefix: "$",
    //   name: "total_cost_to_ETCS",
    //   controls: false,
    //   step: "0.01",
    // },
    // {
    //   label: "Excessive cost To ETCS",
    //   inputType: "number",
    //   name: "excess_cost_to_ETCS",
    //   controls: false,
    //   step: "0.01",
    // },
    {
      label: "Excessive cost To ETCS(USD)",
      inputType: "number_computed",
      computeElements: ["substract", "final_invoice_to_ETCS", "po_value"],
      name: "excess_cost_to_ETCS",
      controls: false,
      step: "0.01",
    },
  ],
  filterSchema: {
    title: "Filter Shipment Records",
    filters: [
      {
        label: "Customer",
        fld: "customer_name",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "short_name",
        optionSource: "tbl_Customers",
        optionDisplayField: ["short_name", "country"],
      },
      {
        label: "Program Name",
        fld: "program_name",
        inputType: "select",
        optionSource: "tbl_Programs",
        name: "program_name",
        type: "select",
        value: "",
      },
      {
        label: "Job #",
        fld: "job_no",
        type: "select",
        inputType: "select",
        inputType: "select",
        optionSource: "tbl_Jobs",
        value: "",
      },
      {
        label: "Tracking Number",
        type: "text",
        fld: "tracking_number",
        value:""
      },
      {
        label: "PO Status",
        fld: "po_to_ETCS",
        type: "instant_select",
        options: ["Awaiting", "Yes", "No", "Email Approved"],
        value: "",
      },

      {
        label: "Die Shop",
        fld: "die_shop",
        type: "select",
        value: "",
        isForeignKey: true,
        keyRenderFld: "name",
        optionSource: "tbl_Suppliers",
        optionDisplayField: ["short_name", "country"],
      },
      {
        label: "Shipper",
        fld: "shipper",
        optionSource: "tbl_Suppliers",
        optionDisplayField: ["short_name", "country"],
        isForeignKey: true,
        keyRenderFld: "short_name",
        type: "select",
        value: "",
      },
      {
        label: "Destination",
        fld: "destination",
        type: "text",
        value: "",
      },
      // Dates Filter
      {
        fld: "pickup_date",
        label: "Pick Up Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      {
        fld: "delivery_date",
        label: "Delivery Date",
        type: "date_from_to",
        from: null,
        to: null,
      },
      // {
      //   fld: "close_date",
      //   label:"Closed Date",
      //   type: "date_from_to",
      //   from: null,
      //   to: null,
      // },
      // {
      //   label: "Responsible Person",
      //   fld: "responsible_person",
      //   type: "select",
      //   value: "",
      //   isForeignKey: true,
      //   keyRenderFld: "name",
      //   optionSource: "tbl_Users",
      //   optionDisplayField: "name",
      // },
    ],
  },
};

const mixed = mix({}, schema, schemaMixin);

export default mixed;
